# Generated by Django 3.2.8 on 2021-11-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placemento_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='hr_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=50)),
                ('year', models.IntegerField(max_length=10)),
                ('rollno', models.IntegerField(max_length=20)),
                ('skills', models.CharField(max_length=500)),
            ],
        ),
    ]
